port = 3700

# If you are a poe subscriber, you can find your API key on the poe official website. You must be a poe subscriber.
#如果你是poe订阅者，你可以在poe官网找到API_key,你必须是poe订阅者。
# POE API密钥列表
apikey = ["jrIwXH1uAhEglnsnwH_i1lqIPiVwxaF083AykiXCmtQ"] 

# Custom API Access Key.自定义接口访问密钥
accessTokens = ["sk-yn-072b39b5-bd92-4b89-9c93-6e425a6810a8"]

# The proxy that will be used to connect to poe.com. Leave it blank if you do not use a proxy
proxy = ""

timeout = 120  # 设置超时时间

# LinuxDO OAuth Configuration
base_url = "https://localhost:3700"  # Your application's base URL
db_url = ""  # SQLite database path
LINUXDO_CLIENT_KEY=""
LINUXDO_CLIENT_SECRET=""
LINUXDO_MIN_LEVEL=

# Session configuration
session_secret = ""  # Replace with a secure random string

bot_names = [
    "Assistant", 
    "GPT-3.5-Turbo", 
    "GPT-3.5-Turbo-16k", 
    "GPT-3.5-Turbo-lnstruct", 
    "GPT-4o", 
    "GPT-4o-128k",
    "GPT-4o-Mini", 
    "GPT-4o-Mini-128k", 
    "ChatGPT-4o-Latest", 
    "ChatGPT-4o-Latest-128k", 
    "GPT-4o-Aug-128k",
    "GPT-4o-Aug-128k",
    "o1", 
    "o1-mini", 
    "o1-preview", 
    "o3-mini" ,
    "o3-mini-high",
    "Claude-3.5-Sonnet", 
    "Claude-3.5-Sonnet-200k", 
    "Claude-3.5-Haiku",
    "Claude-3.5-Haiku-200k", 
    "Claude-3.5-Sonnet-June", 
    "Claude-3.5-Sonnet-June-200k", 
    "Claude-3-opus",
    "Claude-3-opus-200k", 
    "Claude-3-Sonnet", 
    "Claude-3-Sonnet-200k", 
    "Claude-3-Haiku", 
    "Claude-3-Haiku-200k",
    "Gemini-2.0-Flash","Gemini-1.5-Pro", 
    "Gemini-1.5-Pro-Search", 
    "Gemini-1.5-Pro-128k", 
    "Gemini-1.5-Pro-2M", 
    "Gemini-1.5-Flash",
    "Gemini-1.5-Flash-Search", 
    "Gemini-1.5-Flash-128k", 
    "Gemini-1.5-Flash-1M", 
    "Gemini-2.0-Pro", 
    "DeepSeek-R1", 
    "Grok-beta","Qwen-QwQ-32b-preview",
    "Qwen-2.5-Coder-32B-T", 
    "Qwen-2.5-72B-T", 
    "Llama-3.1-405B", 
    "Llama-3.1-405B-T", 
    "Llama-3.1-405B-FP16",
    "Llama-3.1-405B-FW-128k", 
    "Llama-3.1-70B", 
    "Llama-3.1-70B-FP16", 
    "Llama-3.1-70B-T-128k",
    "Llama-3.1-70B-FW-128k", 
    "Llama-3.1-8B", 
    "Llama-3.1-8B-FP16", 
    "Llama-3.1-8B-T-128k", 
    "DALL-E-3",
    "StableDiffusionXL", 
    "StableDiffusion3.5-T", 
    "StableDiffusion3.5-L", 
    "StableDiffusion3", 
    "SD3-Turbo",
    "FLUX-pro", 
    "FLUX-pro-1.1", 
    "FLUX-pro-1.1-T", 
    "FLUX-pro-1.1-ultra", 
    "FLUX-schnell", 
    "FLUX-dev",
    "Luma-Photon", 
    "Luma-Photon-Flash", 
    "Playground-v3", 
    "Ideogram-v2", 
    "Imagen3", 
    "Imagen3-Fast"
]