# 服务器配置
port = 3700
base_url = "https://localhost:3700"
timeout = 120

# 数据库配置
[database]
db_url = "postgresql://user:password@localhost:5432/dbname"
pool_minconn=1
pool_maxconn=20

# 会话配置
session_secret = "your-random-secret-key"  # 使用安全的随机字符串替换

# LinuxDO OAuth 配置
[linuxdo]
client_key = "your-client-key"
client_secret = "your-client-secret"
min_level = 2  # LinuxDO 最低信任等级要求

# API 配置
[api]
# POE API 密钥 (仅限订阅者)
poe_keys = [
    "your-poe-api-key-1",
    "your-poe-api-key-2"
]

# 自定义 API 访问令牌
access_tokens = [
    "sk-yn-your-custom-token-1",
    "sk-yn-your-custom-token-2"
]

# 代理设置 (可选)
proxy = ""  # 例如: "http://127.0.0.1:7890"

# 可用机器人模型
[models]
available = [
    # 常用模型
    "Assistant",
    "GPT-3.5-Turbo",
    "GPT-4o",
    "Claude-3-Sonnet",
    "Gemini-1.5-Pro",
    
    # 图像模型
    "DALL-E-3",
    "StableDiffusionXL"
]